// OLD-format exports must still import (header work, Stage 2, 2026-10-02).
//
// src/__fixtures__/old-exports/*.xlsx are REAL files written by the exporters as they were BEFORE the shared-header change (git da43bc6 / 9640df4): one per importing
// module, each with and without a per-site logo (a logo shifts every old header row down by one). They were generated by running that pre-change App.jsx through the real
// export functions (not hand-typed), so their header rows, merges and per-asset sheets are byte-for-byte what a user's saved exports look like. The CURRENT parsers must read
// every one of them: site / company / ABN / licence and the structure (areas, panels / boards / items / assets), and — for Welder — the exact Brand / Model / Serial that the OLD
// per-welder sheets carried in their header rows ("Brand: ...  |  Model: ...").
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import * as XLSX from 'xlsx';
import { parseExcelToProject, parseIELExcel, parseTATExcel, parseThermoExcel, parseSWBExcel, parseIRTExcel, parseELTExcel, parseWelderExcel, ELT_DEFAULT_TYPES, xjSiteFromTitle } from './App.jsx';

const DIR = path.join(__dirname, '__fixtures__', 'old-exports');
const read = f => XLSX.read(fs.readFileSync(path.join(DIR, f + '.xlsx')), { type: 'buffer' });
const co = { company: 'Example Electrical Pty Ltd', abn: '98 765 432 109', licence: 'EW123456' };
const names = (list, f) => list.map(f);

const PARSE = {
  rcd: d => parseExcelToProject(d, 'Example Quarry', '', '', ''),
  iel: parseIELExcel, tat: parseTATExcel, thermo: d => parseThermoExcel(d, '', XLSX), irt: parseIRTExcel,
  swb: parseSWBExcel, elt: d => parseELTExcel(d, ELT_DEFAULT_TYPES), welder: parseWelderExcel,
};

// What each OLD title yields as the site name: ALWAYS the clean site, for every module. IEL / TAT / Thermo / IRT used to leave module text on an old em-dash title ("Example Quarry — Isolators, E");
// they now strip the known module tail from the END of the title (xjSiteFromTitle), same as SWB / ELT / Welder.
const SITE = {
  rcd: n => expect(n).toBe('Example Quarry'),
  iel: n => expect(n).toBe('Example Quarry'), tat: n => expect(n).toBe('Example Quarry'), thermo: n => expect(n).toBe('Example Quarry'), irt: n => expect(n).toBe('Example Quarry'),
  swb: n => expect(n).toBe('Example Quarry - North'), elt: n => expect(n).toBe('Example Quarry - North'), welder: n => expect(n).toBe('Example Quarry - North'),   // exact-suffix strip keeps the hyphen
};
const STRUCT = {
  rcd: p => { expect(names(p.areas, a => a.name)).toEqual(['Wash Plant', 'Crusher']); const pn = p.areas[0].panels[0]; expect(pn.name).toBe('MSB 1'); expect(pn.circuits).toEqual(['CB1', 'CB2']); expect(pn.circuitMeta.CB1).toMatchObject({ cbType: 'MCB Type B', ampRating: '16A' }); },
  iel: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(Object.values(p.areas[0].panels[0].machineNames)).toEqual(['Conv 1', 'Conv 2']); },
  tat: p => { expect(names(p.areas, a => a.name)).toEqual(['Workshop']); expect(Object.values(p.areas[0].itemNames)).toEqual(['Grinder', 'Drill']); expect(Object.values(p.areas[0].itemTags)).toEqual(['T1', 'T2']); },
  thermo: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(p.areas[0].boards[0].name).toBe('MSB'); expect(Object.values(p.areas[0].boards[0].circuitNames)).toEqual(['One', 'Two']); },
  irt: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(p.areas[0].panels[0].name).toBe('MCC1'); expect(Object.values(p.areas[0].panels[0].itemNames)).toEqual(['Motor 1', 'Motor 2']); },
  swb: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(names(p.areas[0].boards, b => b.name)).toEqual(['MSB', 'DB1']); },
  elt: p => { expect(p.ok).toBe(true); expect(p.assets).toHaveLength(1); expect(p.assets[0]).toMatchObject({ assetId: 'EL-001', assetLocation: 'North Door', fitting: 'Acme Exit 24m' }); },   // the old register listed only the TESTED fitting
  welder: p => {
    expect(p.ok).toBe(true); expect(p.assets).toHaveLength(2);
    // EXACT Brand / Model / Serial come from the OLD per-welder sheet's header strings ("Brand: Acme  |  Model: WeldMaster 200") — this is the part that had to be rewritten
    expect(p.assets[0]).toMatchObject({ location: 'Example Workshop', assetId: 'W001', brand: 'Acme', model: 'WeldMaster 200', serial: 'SN-1001' });
    expect(p.assets[1]).toMatchObject({ location: 'Example Workshop', assetId: 'W002', brand: 'Beta', model: 'Arc 200', serial: 'N/A' });
    expect(p.exact).toBe(2); expect(p.combined).toBe(0);                                                    // both recovered exactly (not the joined-text fallback)
  },
};
// The parsers that return a flat company / ABN / licence (IEL / TAT return them as company / abn / licence too).
const hasCompany = m => true;

describe.each(Object.keys(PARSE))('OLD-format %s export (real file from the pre-change exporter)', mod => {
  it.each(['nologo', 'logo'])('%s: the current parser reads site, company / ABN / licence and the full structure', variant => {
    const parsed = PARSE[mod](read(`${mod}-${variant}`));
    expect(parsed.ok === undefined || parsed.ok === true, JSON.stringify(parsed).slice(0, 200)).toBe(true);
    SITE[mod](parsed.siteName !== undefined ? parsed.siteName : parsed.name);
    if (hasCompany(mod)) expect({ company: parsed.company, abn: parsed.abn, licence: parsed.licence }).toEqual(co);
    STRUCT[mod](parsed);
  });
});

// Hyphenated site names + every known title shape, on the helper AND through each real parser (a workbook whose row 1 is the title).
describe('IEL / TAT / Thermo / IRT: the site name is the title MINUS the known module tail — never split at a dash', () => {
  const MODS = {
    iel:    { parse: parseIELExcel, tail: 'Isolators, E-Stops & Lanyards Test', type: 'Periodic Inspection' },
    tat:    { parse: parseTATExcel, tail: 'Test & Tag', type: 'In-Service Electrical Equipment' },
    thermo: { parse: d => parseThermoExcel(d, '', XLSX), tail: 'Thermographic Test', type: 'Infrared Survey' },
    irt:    { parse: parseIRTExcel, tail: 'Insulation Resistance Test', type: 'Insulation Resistance Readings' },
  };
  const SITES = ['Port-Kembla', 'Hearse Rd - North', 'Example Quarry', 'Bunnings Warehouse - Port-Kembla (Stage 2)'];
  const book = title => { const w = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(w, XLSX.utils.aoa_to_sheet([[title], ['Example Electrical Pty Ltd  |  ABN: 98 765 432 109  |  Electrical Licence: EW123456'], [''], [''], ['Location', 'Type', 'Area', 'Panel / DB', 'Machine', 'Equipment / Circuit', 'Asset ID / Tag', 'Description'], ['Plant', 'estops', 'Plant', 'MCC1', 'M1', 'Motor 1', 'T1', 'Grinder']]), 'S'); return w; };
  describe.each(Object.keys(MODS))('%s', mod => {
    const { parse, tail, type } = MODS[mod];
    it.each(SITES)('"%s": old em-dash title, new en-dash title with a (Test type), and dated / month-tailed old titles all give the site back exactly', site => {
      const titles = [site + ' — ' + tail, site + '  –  ' + tail + '  (' + type + ')', site + ' — ' + tail + ' — 30/09/2026', site + ' — ' + tail + ' — March 2026'];
      titles.forEach(t => { expect(xjSiteFromTitle(t, mod), t).toBe(site); const r = parse(book(t)); expect(r.siteName, 'parser: ' + t).toBe(site); });
    });
    it('a title with NO known module tail is kept whole (never split at a dash)', () => {
      expect(xjSiteFromTitle('Port-Kembla - North Pit', mod)).toBe('Port-Kembla - North Pit');
      expect(parse(book('Port-Kembla')).siteName).toBe('Port-Kembla');
    });
    it('the blank import template ("Site Name — enter your site name here") gives a BLANK site name, so the file name is used (as SWB / ELT / Welder already do)', () => {
      expect(xjSiteFromTitle('Site Name — enter your site name here', mod)).toBe('');
      expect(parse(book('Site Name — enter your site name here')).siteName).toBe('');
    });
  });
  it('only the END of the title is stripped: the module words inside a site name survive', () => {
    expect(xjSiteFromTitle('Test & Tag Depot — Test & Tag', 'tat')).toBe('Test & Tag Depot');
    expect(xjSiteFromTitle('Thermo King Yard - East  –  Thermographic Test  (Infrared Survey)', 'thermo')).toBe('Thermo King Yard - East');
  });
});

describe('the fixtures really are the OLD layout (guards against them being regenerated with the new exporter)', () => {
  const sheet = (f, i = 0) => { const wb = read(f); return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[i]], { header: 1, defval: '' }); };
  it('no-logo: the title is on ROW 1 (the new layout reserves row 1 and puts the title on row 2); with a logo it is on row 2 (row 1 blank)', () => {
    for (const m of ['rcd', 'iel', 'swb', 'elt', 'welder']) {
      expect(String(sheet(`${m}-nologo`)[0][0]), m + ' nologo r1').not.toBe('');
      expect(sheet(`${m}-logo`)[0].every(c => c === ''), m + ' logo r1 blank').toBe(true);
    }
  });
  it('old titles: SWB / ELT / Welder use an EM dash with no "(Test type)" tail; the old Welder per-welder sheet header carries Brand / Model / Serial / Prepared By strings and has no Asset Details block', () => {
    expect(String(sheet('swb-nologo')[0][0])).toBe('Example Quarry - North — Switchboard / Enclosure Audit');
    expect(String(sheet('elt-nologo')[0][0])).toBe('Example Quarry - North — Emergency Lighting Test');
    const per = sheet('welder-nologo', 1).slice(0, 8).map(r => r.filter(c => c !== '').join(' | '));
    expect(per).toEqual(expect.arrayContaining(['Brand: Acme  |  Model: WeldMaster 200', 'Serial Number: SN-1001  |  Date Tested: 30/09/2026', 'Prepared By: Jane Auditor  |  Test Instruments: Test Meter 1000']));
    expect(JSON.stringify(per)).not.toContain('Asset Details');
  });
});
