// OLD-format exports must still import (header work, Stage 2, 2026-10-02).
//
// src/__fixtures__/old-exports/*.xlsx are REAL files written by the exporters as they were BEFORE the shared-header change (git da43bc6 / 9640df4): one per importing
// module, each with and without a per-site logo (a logo shifts every old header row down by one). They were generated by running that pre-change App.jsx through the real
// export functions (not hand-typed), so their header rows, merges and per-asset sheets are byte-for-byte what a user's saved exports look like. The CURRENT parsers must read
// every one of them: site / company / ABN / licence and the structure (areas, panels / boards / items / assets), and — for Welder — the exact Brand / Model / Serial that the OLD
// per-welder sheets carried in their header rows ("Brand: ...  |  Model: ...").
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import * as XLSX from 'xlsx';
import { parseExcelToProject, parseIELExcel, parseTATExcel, parseThermoExcel, parseSWBExcel, parseIRTExcel, parseELTExcel, parseWelderExcel, ELT_DEFAULT_TYPES } from './App.jsx';

const DIR = path.join(__dirname, '__fixtures__', 'old-exports');
const read = f => XLSX.read(fs.readFileSync(path.join(DIR, f + '.xlsx')), { type: 'buffer' });
const co = { company: 'Example Electrical Pty Ltd', abn: '98 765 432 109', licence: 'EW123456' };
const names = (list, f) => list.map(f);

const PARSE = {
  rcd: d => parseExcelToProject(d, 'Example Quarry', '', '', ''),
  iel: parseIELExcel, tat: parseTATExcel, thermo: d => parseThermoExcel(d, '', XLSX), irt: parseIRTExcel,
  swb: parseSWBExcel, elt: d => parseELTExcel(d, ELT_DEFAULT_TYPES), welder: parseWelderExcel,
};

// What each OLD title yields as the site name. IEL / TAT / Thermo / IRT titles use an EM dash ("Site — Module Test"), which those four parsers never stripped — a behaviour that
// predates this work (an old file gave the same value before it); the new en-dash titles ("Site  –  Module  (Type)") do split cleanly. Pinned here so a change is deliberate.
const SITE = {
  rcd: n => expect(n).toBe('Example Quarry'),
  iel: n => expect(n).toMatch(/^Example Quarry/), tat: n => expect(n).toMatch(/^Example Quarry/), thermo: n => expect(n).toMatch(/^Example Quarry/), irt: n => expect(n).toMatch(/^Example Quarry/),
  swb: n => expect(n).toBe('Example Quarry - North'), elt: n => expect(n).toBe('Example Quarry - North'), welder: n => expect(n).toBe('Example Quarry - North'),   // exact-suffix strip keeps the hyphen
};
const STRUCT = {
  rcd: p => { expect(names(p.areas, a => a.name)).toEqual(['Wash Plant', 'Crusher']); const pn = p.areas[0].panels[0]; expect(pn.name).toBe('MSB 1'); expect(pn.circuits).toEqual(['CB1', 'CB2']); expect(pn.circuitMeta.CB1).toMatchObject({ cbType: 'MCB Type B', ampRating: '16A' }); },
  iel: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(Object.values(p.areas[0].panels[0].machineNames)).toEqual(['Conv 1', 'Conv 2']); },
  tat: p => { expect(names(p.areas, a => a.name)).toEqual(['Workshop']); expect(Object.values(p.areas[0].itemNames)).toEqual(['Grinder', 'Drill']); expect(Object.values(p.areas[0].itemTags)).toEqual(['T1', 'T2']); },
  thermo: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(p.areas[0].boards[0].name).toBe('MSB'); expect(Object.values(p.areas[0].boards[0].circuitNames)).toEqual(['One', 'Two']); },
  irt: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(p.areas[0].panels[0].name).toBe('MCC1'); expect(Object.values(p.areas[0].panels[0].itemNames)).toEqual(['Motor 1', 'Motor 2']); },
  swb: p => { expect(names(p.areas, a => a.name)).toEqual(['Plant']); expect(names(p.areas[0].boards, b => b.name)).toEqual(['MSB', 'DB1']); },
  elt: p => { expect(p.ok).toBe(true); expect(p.assets).toHaveLength(1); expect(p.assets[0]).toMatchObject({ assetId: 'EL-001', assetLocation: 'North Door', fitting: 'Acme Exit 24m' }); },   // the old register listed only the TESTED fitting
  welder: p => {
    expect(p.ok).toBe(true); expect(p.assets).toHaveLength(2);
    // EXACT Brand / Model / Serial come from the OLD per-welder sheet's header strings ("Brand: Acme  |  Model: WeldMaster 200") — this is the part that had to be rewritten
    expect(p.assets[0]).toMatchObject({ location: 'Example Workshop', assetId: 'W001', brand: 'Acme', model: 'WeldMaster 200', serial: 'SN-1001' });
    expect(p.assets[1]).toMatchObject({ location: 'Example Workshop', assetId: 'W002', brand: 'Beta', model: 'Arc 200', serial: 'N/A' });
    expect(p.exact).toBe(2); expect(p.combined).toBe(0);                                                    // both recovered exactly (not the joined-text fallback)
  },
};
// The parsers that return a flat company / ABN / licence (IEL / TAT return them as company / abn / licence too).
const hasCompany = m => true;

describe.each(Object.keys(PARSE))('OLD-format %s export (real file from the pre-change exporter)', mod => {
  it.each(['nologo', 'logo'])('%s: the current parser reads site, company / ABN / licence and the full structure', variant => {
    const parsed = PARSE[mod](read(`${mod}-${variant}`));
    expect(parsed.ok === undefined || parsed.ok === true, JSON.stringify(parsed).slice(0, 200)).toBe(true);
    SITE[mod](parsed.siteName !== undefined ? parsed.siteName : parsed.name);
    if (hasCompany(mod)) expect({ company: parsed.company, abn: parsed.abn, licence: parsed.licence }).toEqual(co);
    STRUCT[mod](parsed);
  });
});

describe('the fixtures really are the OLD layout (guards against them being regenerated with the new exporter)', () => {
  const sheet = (f, i = 0) => { const wb = read(f); return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[i]], { header: 1, defval: '' }); };
  it('no-logo: the title is on ROW 1 (the new layout reserves row 1 and puts the title on row 2); with a logo it is on row 2 (row 1 blank)', () => {
    for (const m of ['rcd', 'iel', 'swb', 'elt', 'welder']) {
      expect(String(sheet(`${m}-nologo`)[0][0]), m + ' nologo r1').not.toBe('');
      expect(sheet(`${m}-logo`)[0].every(c => c === ''), m + ' logo r1 blank').toBe(true);
    }
  });
  it('old titles: SWB / ELT / Welder use an EM dash with no "(Test type)" tail; the old Welder per-welder sheet header carries Brand / Model / Serial / Prepared By strings and has no Asset Details block', () => {
    expect(String(sheet('swb-nologo')[0][0])).toBe('Example Quarry - North — Switchboard / Enclosure Audit');
    expect(String(sheet('elt-nologo')[0][0])).toBe('Example Quarry - North — Emergency Lighting Test');
    const per = sheet('welder-nologo', 1).slice(0, 8).map(r => r.filter(c => c !== '').join(' | '));
    expect(per).toEqual(expect.arrayContaining(['Brand: Acme  |  Model: WeldMaster 200', 'Serial Number: SN-1001  |  Date Tested: 30/09/2026', 'Prepared By: Jane Auditor  |  Test Instruments: Test Meter 1000']));
    expect(JSON.stringify(per)).not.toContain('Asset Details');
  });
});
