// REGRESSION: every sheet of every export carries the ONE shared header (xjHeader), identical in structure and — within a module — in text.
// Authority: SparkCheck-assets/header-reference/Header_Reference_FINAL.xlsx. Real exports are generated by the real export functions (live and with a per-site logo), read back
// with ExcelJS, and the logo's anchor / size are read straight from the drawing XML (so the numbers are exactly what Excel gets). If any module's header drifts from the builder, this fails.
import { describe, it, expect, beforeEach, afterEach, beforeAll } from 'vitest';
import ExcelJS from 'exceljs';
import JSZip from 'jszip';
import 'fake-indexeddb/auto';
import { exportExcel, exportIELExcel, exportTATExcel, exportThermoExcel, exportSWBExcel, exportIRTExcel, exportELTExcel, exportWelderExcel, exportGSDExcel, migrateProjectToAreas,
  siteLogoStore, sitePhotoStore, sitePhotoIO, gsdPhotoStore, gsdPhotoIO, xjSheet, xjHdr, xjHeaderRows, XJ_REPORT_TITLES, XJ_HEADER_H, XJ_TABLE_START, XJ_PRIORITY_LEGEND } from './App.jsx';

// ---- tiny PNGs with a REAL header (xjImageSize reads only the IHDR width / height) ----
const png = (w, h) => { const b = Buffer.alloc(33); Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(b, 0); b.writeUInt32BE(13, 8); b.write('IHDR', 12); b.writeUInt32BE(w, 16); b.writeUInt32BE(h, 20); b[24] = 8; b[25] = 2; return b; };
const dataUrl = (w, h) => 'data:image/png;base64,' + png(w, h).toString('base64');
const LOGO = { w: 210, h: 100 };                                   // scales to exactly 105 x 50
const PHOTO = dataUrl(4, 3);

let payload;
beforeAll(() => { sitePhotoIO.imageSize = async () => ({ w: 4, h: 3 }); sitePhotoIO.thumbFromDataUrl = async u => u; sitePhotoIO.exportCopy = async () => ({ dataUrl: PHOTO }); gsdPhotoIO.exportCopy = sitePhotoIO.exportCopy; });
beforeEach(() => { payload = null; window.webkit = { messageHandlers: { shareFile: { postMessage: p => { payload = p; } } } }; });
afterEach(() => { delete window.webkit; });

const co = { company: 'Example Electrical Pty Ltd', abn: '98 765 432 109', licence: 'EW123456' };
const meta = { auditor: 'Jane Auditor', testDate: '2026-09-30', nextTestDate: '2027-09-30', pushDate: '2026-09-30', injectDate: '2026-09-30', nextPushDate: '2026-10-30', nextInjectDate: '2027-09-30', machine: 'Test Machine 1', instruments: 'Test Meter 1000' };
const defect = { defectId: 'D1', rectified: 'Scheduled for Repair', responsibility: 'Client', priority: 'H', notes: 'bad' };
const SITE = 'Example Quarry';
const COLINE = 'Example Electrical Pty Ltd  |  ABN: 98 765 432 109  |  Electrical Licence: EW123456';
const AUD = 'Auditor: Jane Auditor  |  Date Tested: 30/09/2026  |  ';
const pass4 = { visual: 'pass', discharge: 'pass', switching: 'pass', charging: 'pass' };

// ---- one case per export: how to run it, the exact header text, and each sheet's name / first row-6 cell / table column count (n omitted = count the row-6 cells) ----
const CASES = [
  { id: 'rcd-push', title: `${SITE}  –  RCD & ELR Test  (Push Test)`, meta: AUD + 'Next Push Test Due: 30/10/2026', defects: 1, file: /RCD_Push/,
    run: pid => exportExcel({ [pid]: { a: { pn: { C1: { push: { status: 'fail', ...defect } }, C2: { push: { status: 'pass' } } } } } }, { id: pid, name: SITE, ...co, areas: [{ id: 'a', name: 'Plant', panels: [{ id: 'pn', name: 'MSB', circuits: ['C1', 'C2'], circuitMeta: {} }] }] }, meta, 'push', null),
    sheets: [['Push Test', '#'], ['Defects', '#'], ['Summary', `${SITE} – RCD Test Summary`, 2]] },
  { id: 'rcd-inject', title: `${SITE}  –  RCD & ELR Test  (Injection Test)`, meta: AUD + 'Next Injection Test Due: 30/09/2027', defects: 1, file: /RCD_Injection/,
    run: pid => exportExcel({ [pid]: { a: { pn: { C1: { inject: { status: 'fail', resultPos: '>300', resultNeg: '20', ...defect } }, C2: { inject: { status: 'pass', resultPos: '10', resultNeg: '11' } } } } } }, { id: pid, name: SITE, ...co, areas: [{ id: 'a', name: 'Plant', panels: [{ id: 'pn', name: 'MSB', circuits: ['C1', 'C2'], circuitMeta: {} }] }] }, meta, 'inject', null),
    sheets: [['Injection Test', '#'], ['Defects', '#'], ['Summary', `${SITE} – RCD Test Summary`, 2]] },
  { id: 'iel', title: `${SITE}  –  Isolators, E-Stops & Lanyards Test  (Periodic Inspection)`, meta: AUD + 'Next Test Due: 30/09/2027', defects: 1, file: /^IEL_/,
    run: pid => exportIELExcel({ id: pid, name: SITE, ...co, areas: [{ id: 'a', name: 'Plant', panels: [{ id: 'p1', name: 'estops', circuits: ['x', 'y'], machineNames: { x: 'Conv 1', y: 'Conv 2' } }] }] }, { a: { estops: { x: { status: 'fail', lastTested: '2026-09-30', ...defect }, y: { status: 'pass', lastTested: '2026-09-30' } } } }, meta),
    sheets: [['Isolators EStops Lanyards', '#'], ['Defects', '#']] },
  { id: 'tat', title: `${SITE}  –  Test & Tag  (In-Service Electrical Equipment)`, meta: AUD + 'Next Test Due (earliest): 30/12/2026', defects: 1, file: /^TAT_/,
    run: pid => exportTATExcel({ id: pid, name: SITE, ...co, areas: [{ id: 'a', name: 'Workshop', defaultFreq: '3', items: ['x', 'y'], itemNames: { x: 'Grinder', y: 'Drill' }, itemTags: { x: 'T1', y: 'T2' }, itemEquipTypes: {}, itemFreqs: { x: '3', y: '3' } }] }, { a: { x: { status: 'pass', lastTested: '2026-09-30' }, y: { status: 'fail', lastTested: '2026-09-30', ...defect } } }, meta),
    sheets: [['Test & Tag', '#'], ['Defects', '#']] },
  { id: 'thermo', title: `${SITE}  –  Thermographic Test  (Infrared Survey)`, meta: AUD + 'Next Test Due: 30/09/2027', defects: 0, file: /^Thermo_/,
    run: pid => exportThermoExcel({ id: pid, name: SITE, ...co, areas: [{ id: 'a', name: 'Plant', boards: [{ id: 'b', name: 'MSB', circuits: ['c1'], circuitNames: { c1: 'One' } }] }] }, {}, meta),
    sheets: [['Thermographic Test', '#'], ['Defects', '#']] },
  { id: 'irt', title: `${SITE}  –  Insulation Resistance Test  (Insulation Resistance Readings)`, meta: AUD + 'Next Test Due: 30/09/2027', defects: 0, file: /^IR_Test_/,
    run: pid => exportIRTExcel({ id: pid, name: SITE, ...co, areas: [{ id: 'a', name: 'Plant', panels: [{ id: 'pn', name: 'MCC1', items: ['x'], itemNames: { x: 'Motor 1' } }] }] }, {}, meta),
    sheets: [['Register', '#'], ['Readings', '#'], ['Defects', '#']] },
  { id: 'swb', title: `${SITE}  –  Switchboard / Enclosure Audit  (Visual Inspection)`, meta: AUD + 'Next Audit Due: 30/09/2027', file: /^SWB_/,
    run: pid => exportSWBExcel({ id: pid, name: SITE, ...co, areas: [{ id: 'ar', name: 'Plant', boards: [{ id: 'b1', name: 'MSB' }, { id: 'b2', name: 'DB1' }] }] }, {}, meta),
    sheets: [['Register', 'Area'], ['MSB', 'Asset Details', 8], ['DB1', 'Asset Details', 8]] },
  { id: 'elt', title: `${SITE}  –  Emergency Lighting Test  (AS/NZS 2293.2:2019)`, meta: AUD + 'Next Test Due: 30/09/2027', defects: 1, file: /^ELT_/, photos: true,
    run: async pid => { await sitePhotoStore.put('ph1', { buf: new Uint8Array([1]).buffer, type: 'image/png' });
      await exportELTExcel(migrateProjectToAreas({ id: pid, name: SITE, ...co, assets: [{ id: 'a1', location: SITE, assetLocation: 'North Door', assetId: 'EL-1', type: 'Emergency Exit Sign', maintained: 'Maintained', fitting: 'X' }, { id: 'a2', location: SITE, assetLocation: 'South Roof', assetId: 'EL-2', type: 'Emergency Exit Sign', maintained: 'Maintained', fitting: 'Y' }] }),
        { [pid]: { a1: { ...pass4, photos: [{ id: 'ph1', w: 4, h: 3 }] }, a2: { ...pass4, visual: 'fail', ...defect } } }, meta); },
    sheets: [['Emergency Lighting', '#'], ['Defects', '#'], ['Photos', 'Location']] },
  { id: 'welder', title: `${SITE}  –  Welder Test  (Inspection & Audit Checklist)`, meta: AUD + 'Next Test Due: 30/09/2027', file: /^Welder_/,
    run: pid => exportWelderExcel(migrateProjectToAreas({ id: pid, name: SITE, ...co, assets: [{ id: 'a1', location: 'Example Workshop', assetId: 'W001', brand: 'Acme', model: 'WeldMaster 200', serial: 'SN-1001' }, { id: 'a2', location: 'Example Workshop', assetId: 'W002', brand: 'Beta', model: 'Arc 200', serial: 'N/A' }] }), {}, meta),
    sheets: [['Register', 'Location'], ['W001', 'Asset Details', 5], ['W002', 'Asset Details', 5]] },
  { id: 'gsd', title: `${SITE}  –  General Site Defects  (Punch-List Report)`, meta: AUD + 'Next Audit Due: 30/09/2027', file: /^Site_Defects_/, photos: true,
    run: async pid => { await gsdPhotoStore.put('g1', { buf: new Uint8Array([1]).buffer, type: 'image/png' });
      await exportGSDExcel({ id: pid, name: SITE, ...co, areas: [{ id: 'a1', name: 'Area 1' }] }, [{ id: 'i1', areaId: 'a1', assetLocation: 'x', category: 'c', commonDefect: '', description: 'd', photos: [{ id: 'g1', w: 300, h: 400 }], priority: 'H', responsibility: '', dueDate: '' }], meta); },
    sheets: [['Defects Report', 'Area 1', 5], ['Register', '#']] },
];

// ---- read a real export back ----
const colPx = (ws, c) => (ws.getColumn(c).width || 8.43) * 7 + 5;
const widthPx = (ws, n) => { let w = 0; for (let c = 1; c <= n; c++) w += colPx(ws, c); return w; };
const colName = n => { let s = ''; while (n > 0) { const r = (n - 1) % 26; s = String.fromCharCode(65 + r) + s; n = Math.floor((n - 1) / 26); } return s; };
const txt = c => (c.value == null ? '' : String(c.value));
async function readExport() {
  const buf = Buffer.from(payload.base64, 'base64'); const wb = new ExcelJS.Workbook(); await wb.xlsx.load(buf); const zip = await JSZip.loadAsync(buf);
  const drawings = [];                                                                   // per sheet: [{ row, col, colOff, rowOff, cx, cy }] (EMU, straight from the drawing XML)
  for (let i = 0; i < wb.worksheets.length; i++) {
    const rels = zip.file(`xl/worksheets/_rels/sheet${i + 1}.xml.rels`); const list = [];
    if (rels) { const target = ((await rels.async('string')).match(/Target="\.\.\/drawings\/(drawing\d+\.xml)"/) || [])[1];
      if (target) { const x = await zip.file('xl/drawings/' + target).async('string');
        for (const m of x.matchAll(/<(?:xdr:)?(?:one|two)CellAnchor[\s\S]*?<\/(?:xdr:)?(?:one|two)CellAnchor>/g)) { const g = (tag, s) => +((s.match(new RegExp(`<(?:xdr:)?${tag}>(\\d+)</`)) || [])[1] || 0);
          const from = m[0].match(/<(?:xdr:)?from>[\s\S]*?<\/(?:xdr:)?from>/)[0]; const ext = m[0].match(/<(?:xdr:)?ext [^>]*cx="(\d+)" cy="(\d+)"/);
          list.push({ col: g('col', from), colOff: g('colOff', from), row: g('row', from), rowOff: g('rowOff', from), cx: +ext[1], cy: +ext[2] }); } } }
    drawings.push(list);
  }
  return { wb, drawings, filename: payload.filename };
}
const merges = ws => Object.values(ws._merges).map(m => m.range);

describe.each(CASES)('$id: every sheet carries the shared header', c => {
  it.each(['nologo', 'logo'])('%s', async variant => {
    const pid = `p-${c.id}-${variant}`;
    if (variant === 'logo') await siteLogoStore.put(c.id.split('-')[0], pid, { buf: png(LOGO.w, LOGO.h), type: 'image/png' });
    try {
      await c.run(pid); const { wb, drawings } = await readExport();
      expect(wb.worksheets.map(w => w.name)).toEqual(c.sheets.map(s => s[0]));                   // tab names are unchanged
      wb.worksheets.forEach((ws, i) => {
        const [name, first6, nExplicit] = c.sheets[i]; const at = `${c.id}/${name}`;
        // rows 1-5: text + heights, identical on every sheet of the module
        expect([1, 2, 3, 4, 5].map(r => txt(ws.getCell(r, 1))), at).toEqual(['', c.title, COLINE, c.meta, '']);
        expect([1, 2, 3, 4, 5].map(r => ws.getRow(r).height), at).toEqual(XJ_HEADER_H);
        // the table (or first content row) starts on row 6
        expect(txt(ws.getCell(XJ_TABLE_START, 1)), at + ' row 6').toBe(first6);
        // each of the 5 rows is ONE merge from A across the same last column; that column is the table's last (widened only when the sheet is narrower than 640px)
        let nTable = nExplicit; if (!nTable) { nTable = 0; ws.getRow(XJ_TABLE_START).eachCell({ includeEmpty: false }, (_, col) => { nTable = Math.max(nTable, col); }); }
        const m = merges(ws); const ends = [1, 2, 3, 4, 5].map(r => { const hit = m.find(x => new RegExp(`^A${r}:[A-Z]+${r}$`).test(x)); expect(hit, `${at} merge row ${r}`).toBeTruthy(); return hit.split(':')[1].replace(/\d+/, ''); });
        expect(new Set(ends).size, at + ' same merge end on every header row').toBe(1);
        let last = nTable; while (widthPx(ws, last) < 640) last++;
        expect(ends[0], at + ' merge end').toBe(colName(last));
        // look: Calibri default, not bold, no fill, NO border, horizontal-centre ONLY (rows 2-4); rows 1 and 5 unstyled
        [2, 3, 4].forEach(r => { const cell = ws.getCell(r, 1); expect(cell.alignment, `${at} r${r}`).toMatchObject({ horizontal: 'center' }); expect(cell.alignment.vertical, `${at} r${r} vertical`).toBeUndefined(); });
        [1, 2, 3, 4, 5].forEach(r => { const cell = ws.getCell(r, 1); expect(!cell.font || !cell.font.bold, at + ' bold').toBe(true); expect(!cell.fill || cell.fill.pattern === 'none', at + ' fill').toBe(true); expect(!cell.border || Object.keys(cell.border).length === 0, `${at} r${r} border`).toBe(true); });
        // images: the logo (and only it) sits in row 1; photos start below the header
        const imgs = drawings[i]; const inHeader = imgs.filter(d => d.row === 0); const below = imgs.filter(d => d.row > 0);
        expect(inHeader, at + ' header images').toHaveLength(variant === 'logo' ? 1 : 0);
        below.forEach(d => expect(d.row, at + ' photo row').toBeGreaterThanOrEqual(5));
        if (c.photos && ['Photos', 'Defects Report'].includes(name)) expect(below.length, at + ' photos present').toBeGreaterThan(0);
        if (variant === 'logo') {
          const d = inHeader[0];
          expect([d.cx / 9525, d.cy / 9525], at + ' logo size').toEqual([105, 50]);                // 210 x 100 -> exactly the 105 x 50 box
          let left = 0; for (let k = 1; k <= d.col; k++) left += colPx(ws, k);
          const centreX = left + d.colOff / 9525 + d.cx / 9525 / 2;
          expect(Math.abs(centreX - widthPx(ws, last) / 2), `${at} logo centred horizontally over the merged width (${centreX} vs ${widthPx(ws, last) / 2})`).toBeLessThanOrEqual(1);
          const centreY = d.rowOff / 9525 + d.cy / 9525 / 2; expect(Math.abs(centreY - (XJ_HEADER_H[0] * 96 / 72) / 2), at + ' logo centred vertically in row 1').toBeLessThanOrEqual(1);
        }
      });
    } finally { if (variant === 'logo') await siteLogoStore.del(c.id.split('-')[0], pid); }
  });
});

describe('what the shared header must NOT contain, and where the extra details went', () => {
  it('no title, sheet name or filename states a test interval (the interval shows only through the real next-due date)', async () => {
    const INTERVAL = /\b(monthly|quarterly|annual(ly)?|yearly|weekly|daily|biennial|\d+\s*-?\s*(month|year|week|day)s?)\b/i;
    for (const [key, t] of Object.entries(XJ_REPORT_TITLES)) { const vs = t.variants ? Object.values(t.variants) : [t]; for (const v of [{ module: t.module }, ...vs]) for (const s of [v.module, v.type, v.next].filter(Boolean)) expect(s, `XJ_REPORT_TITLES.${key}`).not.toMatch(INTERVAL); }
    for (const c of CASES) { const pid = 'p-int-' + c.id; await c.run(pid); const { wb, filename } = await readExport();
      expect(filename, c.id + ' filename').not.toMatch(INTERVAL); wb.worksheets.forEach(ws => { expect(ws.name, c.id).not.toMatch(INTERVAL); [2, 3, 4].forEach(r => { const s = txt(ws.getCell(r, 1)); expect(s.replace(/Next [A-Za-z() ]*Due[^:]*:/, ''), `${c.id}/${ws.name} r${r}`).not.toMatch(INTERVAL); }); }); }
  });
  it('the Defects footer (always written) carries a count COMPUTED from the real rows, then the priority legend — with 0 defects and with some', async () => {
    for (const c of CASES.filter(x => x.defects !== undefined)) { await c.run('p-def-' + c.id); const { wb } = await readExport(); const ws = wb.getWorksheet('Defects');
      const lines = []; ws.eachRow(row => lines.push(txt(row.getCell(1))));
      const rows = lines.filter((l, i) => i >= 5 && /^\d+$/.test(l)).length;                          // numbered defect rows under the table headings
      expect(rows, c.id + ' defect rows').toBe(c.defects);
      const k = lines.indexOf(`Defects recorded: ${rows}`); expect(k, `${c.id} count line`).toBeGreaterThan(5);
      expect(lines[k + 1], c.id + ' legend follows the count').toBe(XJ_PRIORITY_LEGEND);
      if (!c.defects) expect(txt(ws.getCell(7, 1)), c.id + ' empty line').toBe('No defects recorded');
    }
  });
  it('Welder: no "Prepared By" anywhere (it was always the Auditor); the asset identity + Test Instruments are an Asset Details block from row 6', async () => {
    const c = CASES.find(x => x.id === 'welder'); await c.run('p-w-det'); const { wb } = await readExport(); const w = wb.getWorksheet('W001');
    expect(JSON.stringify(wb.worksheets.map(s => s.getSheetValues()))).not.toMatch(/Prepared By/);
    expect([6, 7, 8, 9, 10, 11, 12].map(r => txt(w.getCell(r, 1)))).toEqual(['Asset Details', 'Location', 'Asset ID', 'Brand', 'Model', 'Serial Number', 'Test Instruments']);
    expect([7, 8, 9, 10, 11, 12].map(r => txt(w.getCell(r, 2)))).toEqual(['Example Workshop', 'W001', 'Acme', 'WeldMaster 200', 'SN-1001', 'Test Meter 1000']);
    expect(txt(w.getCell(14, 1))).toBe('Audit Summary');
  });
});

describe('the logo is sized and placed exactly like the reference file', () => {
  // Reference (Header_Reference_FINAL.xlsx, RCD "Injection Test"): columns 5,16,22,12,8,13,11,11,11,24,13 merged A:K; a 105 x 50 logo anchored at col 5, colOff 190500 EMU, rowOff 52387 EMU.
  const build = (w, h, widths = [5, 16, 22, 12, 8, 13, 11, 11, 11, 24, 13]) => { const wb = new ExcelJS.Workbook(); const hdr = xjHdr('rcd', { variant: 'inject', site: SITE, ...co, auditor: 'Jane Auditor', testDate: '30/09/2026', nextDue: '30/09/2027', logo: dataUrl(w, h) });
    xjSheet(wb, 'S', { hdr, headers: widths.map((_, i) => 'H' + i), widths, rows: [] }); return wb; };
  const anchorOf = async wb => { const z = await JSZip.loadAsync(Buffer.from(await wb.xlsx.writeBuffer())); const x = await z.file('xl/drawings/drawing1.xml').async('string'); const g = (tag, s) => +((s.match(new RegExp(`<(?:xdr:)?${tag}>(\\d+)</`)) || [])[1]);
    const from = x.match(/<(?:xdr:)?from>[\s\S]*?<\/(?:xdr:)?from>/)[0]; const ext = x.match(/<(?:xdr:)?ext [^>]*cx="(\d+)" cy="(\d+)"/); return { col: g('col', from), colOff: g('colOff', from), row: g('row', from), rowOff: g('rowOff', from), cx: +ext[1], cy: +ext[2] }; };
  it('a 210 x 100 logo reproduces the reference anchor: column 5, colOff 190500 EMU, rowOff 52387 EMU, 1000125 x 476250 EMU', async () => {
    const a = await anchorOf(build(210, 100));
    expect(a.col).toBe(5); expect(Math.abs(a.colOff - 190500)).toBeLessThanOrEqual(10); expect(a.row).toBe(0); expect(Math.abs(a.rowOff - 52387)).toBeLessThanOrEqual(10); expect([a.cx, a.cy]).toEqual([1000125, 476250]);
  });
  it('fits INSIDE 105 x 50 keeping its aspect; never stretched; never enlarged past its native size', async () => {
    const px = async (w, h) => { const a = await anchorOf(build(w, h)); return [a.cx / 9525, a.cy / 9525]; };
    expect(await px(100, 200)).toEqual([25, 50]);                // portrait: height-limited
    expect(await px(400, 100)).toEqual([105, 26]);               // wide: width-limited (26.25 -> 26)
    expect(await px(60, 30)).toEqual([60, 30]);                  // smaller than the box: left at native size
    expect(await px(1, 1)).toEqual([1, 1]);
  });
  it('is never wider than a very narrow sheet, and stays centred on it', async () => {
    const wb = build(210, 100, [3, 3]); const a = await anchorOf(wb);   // 2 narrow columns: widened to the 640px minimum, so the logo is still 105 wide and centred on THAT width
    expect(a.cx / 9525).toBe(105); const ws = wb.getWorksheet('S'); let left = 0; for (let k = 1; k <= a.col; k++) left += colPx(ws, k);
    let last = 2; while (widthPx(ws, last) < 640) last++;
    expect(Math.abs(left + a.colOff / 9525 + 52.5 - widthPx(ws, last) / 2)).toBeLessThanOrEqual(1);
  });
});

describe('the builder itself (single source of truth)', () => {
  it('xjHeaderRows gives the five rows of the spec, with the exact RCD example wording', () => {
    const rows = xjHeaderRows(xjHdr('rcd', { variant: 'inject', site: 'Example Quarry', ...co, auditor: 'Jane Auditor', testDate: '30/09/2026', nextDue: '30/09/2027' }));
    expect(rows).toEqual([['', 45.75], ['Example Quarry  –  RCD & ELR Test  (Injection Test)', 31.5], [COLINE, 15.75], ['Auditor: Jane Auditor  |  Date Tested: 30/09/2026  |  Next Injection Test Due: 30/09/2027', 15.75], ['', 6]]);
  });
  it('every module has a title entry, and the table always starts on row 6', () => {
    expect(Object.keys(XJ_REPORT_TITLES).sort()).toEqual(['elt', 'gsd', 'iel', 'irt', 'rcd', 'swb', 'tat', 'thermo', 'welder']);
    expect(XJ_TABLE_START).toBe(6);
  });
});
